[build]
target = "aarch64-linux-android"

[env]
BINDGEN_EXTRA_CLANG_ARGS = "--std=c++17 -DANDROID_PLATFORM -I../../ndk/include_platform"
ANDROID_NDK_HOME = "/Users/user/Library/Android/sdk/ndk/27.2.12479018"
CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = "/Users/user/Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android31-clang"

[profile.release]
strip = "symbols"
